export default function AboutPageTab() {
  return (
    <section className="panel" style={{ textAlign: "center", maxWidth: "900px", margin: "0 auto", padding: "2rem" }}>
      <div style={{ lineHeight: "1.8", fontSize: "1rem", textAlign: "center" }}>
        <p style={{ marginBottom: "1.5rem" }}>
          My name is Shirin Alapati and I am a second-year student at San José State University majoring in data science. While I respect the loads of content taught in the classroom, I try to also gain knowledge related to my major outside of the classroom by joining clubs and doing personal projects. I enjoy incorporating concepts from data science and being innovative in software engineering to produce unique insights in any field. However, with my main hobbies being sports and history, I enjoy producing insights in those areas to more efficiently understand key points and themes in them. This is a major reason why baseball is my favorite sport as it's definitely the most analytical sport with so much data and numbers involved with every pitch and swing. Playing it since I was little and growing up with the Athletics as my first favorite sports team, I've had an extremely strong affinity for baseball. It is a very unique game with so many dynamics as I love the game because I think it's cool how it is the only sport where the defense controls the ball. One thing that I make sure I never miss annually is the postseason because this is what massively separates it from any other sport. The energy, the fans rising in sync for each big strikeout or home run, and the unlikely heroes that make a name for themselves forever make it not just a sport, but something us fans can learn a lot from. Overall, I enjoy the interconnectedness of computer science and the creativity it enables, which is why this assignment was especially meaningful to me. It gave me the chance to bring together technology and baseball, two things I love, into one.
        </p>

        <p style={{ marginBottom: "1.5rem", fontWeight: "600" }}>
          *IMPORTANT NOTE: The README.md file in the submission provides instructions on how to run my app and what dependencies it has.
        </p>

        <p style={{ marginBottom: "1.5rem" }}>
          My submission has three different tabs in order from left to right titled "Main," "Free Agents," and "Stuff Score." In the Main tab, users choose a pitcher from a dropdown list that has the pitchers in the assignment. After clicking on a pitcher, the summary table will be displayed of the different statistics for each pitch they throw. There are nine columns that include all the requirements listed from 2a-2f in the assignment, with the ninth column printing the pitch type. So, the Main tab has everything that satisfies the initial requirements of the assignment. However, above each pitcher's table, my submission also includes a scatter plot that visualizes the average movement profile for each of the pitcher's pitch types. Horizontal break is shown on the x-axis, while induced vertical break is shown on the y-axis. Each pitch type is represented by a different colored dot, with a legend provided to help users interpret the dots. If a pitcher throws five different pitch types, five colored points will appear on the plot, each reflecting the average movement profile of that pitch. Above the plot, I also include a short one-line summary highlighting key details from the pitcher's table. Specifically, it's their most-used pitch, their hardest pitch, and their best soft-contact pitch, based on what pitch generates the lowest average exit velocity.
        </p>

        <p style={{ marginBottom: "1.5rem" }}>
          The next tab called Free Agents gives users an opportunity to compare a 2025 free agent starting pitcher with a Nationals starting pitcher. I tried to include as many free agent starting pitchers, but the database tracked 46, meaning that users can pick from a dropdown list of 46 starting pitchers currently on the market. They are then meant to compare it with one of 4 Nationals starting pitchers, based on which 4 made the most starts in 2025. This is unfortunate because Josiah Gray isn't on the list since he missed the full 2025 season. This tab has the same features for each pitcher that were on the main tab, including the table and the scatterplot. One can see a free agent and a Nationals pitcher's pitch details on one screen, allowing them to easily compare. In conclusion, this gives one a chance to highlight meaningful differences between the repertoires of free-agent starters and current Nationals starters, helping a member of the Nationals Baseball Operations potentially identify a free-agent they like.
        </p>

        <p style={{ marginBottom: "1.5rem" }}>
          The final Stuff Score Tab ranks all the 46 free-agents in a leaderboard based on their stuff score, which is calculated from a formula I designed. The formula is explained more on the tab, but the bottom line is that it incorporates all the metrics included in each pitcher's table, which are overall velocity, total horizontal movement, total vertical movement, average spin rate, average exit hit velocity allowed, and average launch angle allowed. Due to this dataset being so large, I tried to take advantage of it by doing more than the initial requirements. I thought doing something with the major free agent starters would be a good idea because so many times, World Series titles are won due to signings made in the offseason. As a result, from illustrating the repertoires of all free agents and based on the limited metrics given, I decided to create a stuff score to highlight any attractive pitchers on the open market right now.
        </p>
      </div>
    </section>
  );
}

